version: '3'
services:
  ms-service-registry-server-1:
    image: "org.sj/ms-service-registry-server"
    container_name: ms-service-registry-server-1
    command: -Dspring.profiles.active=server1 -Deureka.client.serviceUrl.defaultZone=http://ms-service-registry-server-2:8762/eureka org.sj.msserviceregistryserver.MsServiceRegistryServerApplication
    ports:
           - 8761:8761
  ms-service-registry-server-2:  
    image: "org.sj/ms-service-registry-server"
    container_name: ms-service-registry-server-2
    command: -Dspring.profiles.active=server2 -Deureka.client.serviceUrl.defaultZone=http://ms-service-registry-server-1:8761/eureka org.sj.msserviceregistryserver.MsServiceRegistryServerApplication
    ports:
           - 8762:8762
  ms-config-server:
    image: "org.sj/ms-config-server"
    container_name: ms-config-server
    command: -Dserver.port=9999 -Dspring.profiles.active=native -Dspring.cloud.config.server.native.searchLocations=file:///\_fsconfig -Deureka.client.serviceUrl.defaultZone=http://ms-service-registry-server-1:8761/eureka/  org.sj.msconfigserver.MsConfigServerApplication
    ports:
           - 9999:9999  
networks:
  default:
    external:
      name: org-sj-ms